import type { LanguageSnippet } from '../types';

export const cppSnippets: LanguageSnippet[] = [
  {
    label: 'if statement',
    prefix: 'if',
    body: 'if (${1:condition}) {\n\t${2}\n}',
    description: 'if statement',
  },
  {
    label: 'if-else statement',
    prefix: 'ife',
    body: 'if (${1:condition}) {\n\t${2}\n} else {\n\t${3}\n}',
    description: 'if-else statement',
  },
  {
    label: 'else if',
    prefix: 'elif',
    body: 'else if (${1:condition}) {\n\t${2}\n}',
    description: 'else if statement',
  },
  {
    label: 'for loop',
    prefix: 'for',
    body: 'for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n\t${3}\n}',
    description: 'for loop',
  },
  {
    label: 'range-based for',
    prefix: 'forr',
    body: 'for (auto& ${1:item} : ${2:container}) {\n\t${3}\n}',
    description: 'range-based for loop',
  },
  {
    label: 'while loop',
    prefix: 'while',
    body: 'while (${1:condition}) {\n\t${2}\n}',
    description: 'while loop',
  },
  {
    label: 'do-while loop',
    prefix: 'dowhile',
    body: 'do {\n\t${1}\n} while (${2:condition});',
    description: 'do-while loop',
  },
  {
    label: 'switch statement',
    prefix: 'switch',
    body: 'switch (${1:expression}) {\n\tcase ${2:value}:\n\t\t${3}\n\t\tbreak;\n\tdefault:\n\t\t${4}\n\t\tbreak;\n}',
    description: 'switch statement',
  },
  {
    label: 'try-catch',
    prefix: 'try',
    body: 'try {\n\t${1}\n} catch (const ${2:std::exception}& ${3:e}) {\n\t${4}\n}',
    description: 'try-catch block',
  },
  {
    label: 'class',
    prefix: 'class',
    body: 'class ${1:ClassName} {\npublic:\n\t${1:ClassName}();\n\t~${1:ClassName}();\n\nprivate:\n\t${2}\n};',
    description: 'class definition',
  },
  {
    label: 'struct',
    prefix: 'struct',
    body: 'struct ${1:StructName} {\n\t${2}\n};',
    description: 'struct definition',
  },
  {
    label: 'function',
    prefix: 'func',
    body: '${1:void} ${2:functionName}(${3}) {\n\t${4}\n}',
    description: 'function definition',
  },
  {
    label: 'main function',
    prefix: 'main',
    body: 'int main(int argc, char* argv[]) {\n\t${1}\n\treturn 0;\n}',
    description: 'main function',
  },
  {
    label: 'main simple',
    prefix: 'mains',
    body: 'int main() {\n\t${1}\n\treturn 0;\n}',
    description: 'simple main function',
  },
  {
    label: 'include',
    prefix: 'inc',
    body: '#include <${1:iostream}>',
    description: 'include directive',
  },
  {
    label: 'include header',
    prefix: 'inch',
    body: '#include "${1:header.h}"',
    description: 'include header file',
  },
  {
    label: 'header guard',
    prefix: 'guard',
    body: '#ifndef ${1:HEADER_H}\n#define ${1:HEADER_H}\n\n${2}\n\n#endif // ${1:HEADER_H}',
    description: 'header guard',
  },
  {
    label: 'pragma once',
    prefix: 'pragma',
    body: '#pragma once\n\n${1}',
    description: 'pragma once',
  },
  {
    label: 'namespace',
    prefix: 'namespace',
    body: 'namespace ${1:name} {\n\t${2}\n}',
    description: 'namespace definition',
  },
  {
    label: 'cout',
    prefix: 'cout',
    body: 'std::cout << ${1} << std::endl;',
    description: 'cout statement',
  },
  {
    label: 'cin',
    prefix: 'cin',
    body: 'std::cin >> ${1};',
    description: 'cin statement',
  },
  {
    label: 'vector',
    prefix: 'vec',
    body: 'std::vector<${1:int}> ${2:name};',
    description: 'vector declaration',
  },
  {
    label: 'map',
    prefix: 'map',
    body: 'std::map<${1:key}, ${2:value}> ${3:name};',
    description: 'map declaration',
  },
  {
    label: 'unique_ptr',
    prefix: 'uptr',
    body: 'std::unique_ptr<${1:Type}> ${2:ptr} = std::make_unique<${1:Type}>(${3});',
    description: 'unique_ptr',
  },
  {
    label: 'shared_ptr',
    prefix: 'sptr',
    body: 'std::shared_ptr<${1:Type}> ${2:ptr} = std::make_shared<${1:Type}>(${3});',
    description: 'shared_ptr',
  },
  {
    label: 'lambda',
    prefix: 'lambda',
    body: '[${1:capture}](${2:params}) {\n\t${3}\n}',
    description: 'lambda expression',
  },
  {
    label: 'template function',
    prefix: 'template',
    body: 'template <typename ${1:T}>\n${2:T} ${3:functionName}(${4}) {\n\t${5}\n}',
    description: 'template function',
  },
  {
    label: 'template class',
    prefix: 'templatec',
    body: 'template <typename ${1:T}>\nclass ${2:ClassName} {\npublic:\n\t${3}\n};',
    description: 'template class',
  },
];
