import type { LanguageSnippet } from '../types';

export const csharpSnippets: LanguageSnippet[] = [
  {
    label: 'if statement',
    prefix: 'if',
    body: 'if (${1:condition})\n{\n\t${2}\n}',
    description: 'if statement',
  },
  {
    label: 'if-else statement',
    prefix: 'ife',
    body: 'if (${1:condition})\n{\n\t${2}\n}\nelse\n{\n\t${3}\n}',
    description: 'if-else statement',
  },
  {
    label: 'else if',
    prefix: 'elif',
    body: 'else if (${1:condition})\n{\n\t${2}\n}',
    description: 'else if statement',
  },
  {
    label: 'for loop',
    prefix: 'for',
    body: 'for (int ${1:i} = 0; ${1:i} < ${2:length}; ${1:i}++)\n{\n\t${3}\n}',
    description: 'for loop',
  },
  {
    label: 'foreach loop',
    prefix: 'foreach',
    body: 'foreach (var ${1:item} in ${2:collection})\n{\n\t${3}\n}',
    description: 'foreach loop',
  },
  {
    label: 'while loop',
    prefix: 'while',
    body: 'while (${1:condition})\n{\n\t${2}\n}',
    description: 'while loop',
  },
  {
    label: 'do-while loop',
    prefix: 'dowhile',
    body: 'do\n{\n\t${1}\n} while (${2:condition});',
    description: 'do-while loop',
  },
  {
    label: 'switch statement',
    prefix: 'switch',
    body: 'switch (${1:expression})\n{\n\tcase ${2:value}:\n\t\t${3}\n\t\tbreak;\n\tdefault:\n\t\t${4}\n\t\tbreak;\n}',
    description: 'switch statement',
  },
  {
    label: 'try-catch',
    prefix: 'try',
    body: 'try\n{\n\t${1}\n}\ncatch (${2:Exception} ${3:ex})\n{\n\t${4}\n}',
    description: 'try-catch block',
  },
  {
    label: 'try-catch-finally',
    prefix: 'tryf',
    body: 'try\n{\n\t${1}\n}\ncatch (${2:Exception} ${3:ex})\n{\n\t${4}\n}\nfinally\n{\n\t${5}\n}',
    description: 'try-catch-finally block',
  },
  {
    label: 'class',
    prefix: 'class',
    body: 'public class ${1:ClassName}\n{\n\t${2}\n}',
    description: 'class definition',
  },
  {
    label: 'class with constructor',
    prefix: 'classc',
    body: 'public class ${1:ClassName}\n{\n\tpublic ${1:ClassName}(${2})\n\t{\n\t\t${3}\n\t}\n}',
    description: 'class with constructor',
  },
  {
    label: 'interface',
    prefix: 'interface',
    body: 'public interface I${1:Name}\n{\n\t${2}\n}',
    description: 'interface definition',
  },
  {
    label: 'enum',
    prefix: 'enum',
    body: 'public enum ${1:EnumName}\n{\n\t${2:Value1},\n\t${3:Value2}\n}',
    description: 'enum definition',
  },
  {
    label: 'method',
    prefix: 'method',
    body: 'public ${1:void} ${2:MethodName}(${3})\n{\n\t${4}\n}',
    description: 'method definition',
  },
  {
    label: 'async method',
    prefix: 'asyncm',
    body: 'public async Task${1:<T>} ${2:MethodName}Async(${3})\n{\n\t${4}\n}',
    description: 'async method definition',
  },
  {
    label: 'property',
    prefix: 'prop',
    body: 'public ${1:string} ${2:Name} { get; set; }',
    description: 'auto property',
  },
  {
    label: 'property with backing field',
    prefix: 'propf',
    body: 'private ${1:string} _${2:name};\npublic ${1:string} ${3:Name}\n{\n\tget { return _${2:name}; }\n\tset { _${2:name} = value; }\n}',
    description: 'property with backing field',
  },
  {
    label: 'constructor',
    prefix: 'ctor',
    body: 'public ${1:ClassName}(${2})\n{\n\t${3}\n}',
    description: 'constructor',
  },
  {
    label: 'using statement',
    prefix: 'using',
    body: 'using (var ${1:resource} = ${2:expression})\n{\n\t${3}\n}',
    description: 'using statement',
  },
  {
    label: 'namespace',
    prefix: 'namespace',
    body: 'namespace ${1:Name}\n{\n\t${2}\n}',
    description: 'namespace definition',
  },
  {
    label: 'LINQ query',
    prefix: 'linq',
    body: 'var ${1:result} = from ${2:item} in ${3:collection}\n\twhere ${4:condition}\n\tselect ${5:item};',
    description: 'LINQ query expression',
  },
  {
    label: 'lambda expression',
    prefix: 'lambda',
    body: '(${1:x}) => ${2:expression}',
    description: 'lambda expression',
  },
  {
    label: 'Console.WriteLine',
    prefix: 'cw',
    body: 'Console.WriteLine(${1});',
    description: 'Console.WriteLine',
  },
  {
    label: 'record',
    prefix: 'record',
    body: 'public record ${1:RecordName}(${2:string Name});',
    description: 'record definition',
  },
];
