import type { LanguageSnippet } from '../types';

export const javaSnippets: LanguageSnippet[] = [
  {
    label: 'if statement',
    prefix: 'if',
    body: 'if (${1:condition}) {\n\t${2}\n}',
    description: 'if statement',
  },
  {
    label: 'if-else statement',
    prefix: 'ife',
    body: 'if (${1:condition}) {\n\t${2}\n} else {\n\t${3}\n}',
    description: 'if-else statement',
  },
  {
    label: 'else if',
    prefix: 'elif',
    body: 'else if (${1:condition}) {\n\t${2}\n}',
    description: 'else if statement',
  },
  {
    label: 'for loop',
    prefix: 'for',
    body: 'for (int ${1:i} = 0; ${1:i} < ${2:length}; ${1:i}++) {\n\t${3}\n}',
    description: 'for loop',
  },
  {
    label: 'for-each loop',
    prefix: 'foreach',
    body: 'for (${1:Type} ${2:item} : ${3:collection}) {\n\t${4}\n}',
    description: 'for-each loop',
  },
  {
    label: 'while loop',
    prefix: 'while',
    body: 'while (${1:condition}) {\n\t${2}\n}',
    description: 'while loop',
  },
  {
    label: 'do-while loop',
    prefix: 'dowhile',
    body: 'do {\n\t${1}\n} while (${2:condition});',
    description: 'do-while loop',
  },
  {
    label: 'switch statement',
    prefix: 'switch',
    body: 'switch (${1:expression}) {\n\tcase ${2:value}:\n\t\t${3}\n\t\tbreak;\n\tdefault:\n\t\t${4}\n\t\tbreak;\n}',
    description: 'switch statement',
  },
  {
    label: 'try-catch',
    prefix: 'try',
    body: 'try {\n\t${1}\n} catch (${2:Exception} ${3:e}) {\n\t${4}\n}',
    description: 'try-catch block',
  },
  {
    label: 'try-catch-finally',
    prefix: 'tryf',
    body: 'try {\n\t${1}\n} catch (${2:Exception} ${3:e}) {\n\t${4}\n} finally {\n\t${5}\n}',
    description: 'try-catch-finally block',
  },
  {
    label: 'try-with-resources',
    prefix: 'tryr',
    body: 'try (${1:Resource} ${2:res} = ${3:new Resource()}) {\n\t${4}\n} catch (${5:Exception} ${6:e}) {\n\t${7}\n}',
    description: 'try-with-resources block',
  },
  {
    label: 'class',
    prefix: 'class',
    body: 'public class ${1:ClassName} {\n\t${2}\n}',
    description: 'class definition',
  },
  {
    label: 'class with constructor',
    prefix: 'classc',
    body: 'public class ${1:ClassName} {\n\tpublic ${1:ClassName}(${2}) {\n\t\t${3}\n\t}\n}',
    description: 'class with constructor',
  },
  {
    label: 'interface',
    prefix: 'interface',
    body: 'public interface ${1:InterfaceName} {\n\t${2}\n}',
    description: 'interface definition',
  },
  {
    label: 'enum',
    prefix: 'enum',
    body: 'public enum ${1:EnumName} {\n\t${2:VALUE1},\n\t${3:VALUE2}\n}',
    description: 'enum definition',
  },
  {
    label: 'method',
    prefix: 'method',
    body: 'public ${1:void} ${2:methodName}(${3}) {\n\t${4}\n}',
    description: 'method definition',
  },
  {
    label: 'main method',
    prefix: 'main',
    body: 'public static void main(String[] args) {\n\t${1}\n}',
    description: 'main method',
  },
  {
    label: 'constructor',
    prefix: 'ctor',
    body: 'public ${1:ClassName}(${2}) {\n\t${3}\n}',
    description: 'constructor',
  },
  {
    label: 'getter',
    prefix: 'get',
    body: 'public ${1:String} get${2:Name}() {\n\treturn this.${3:name};\n}',
    description: 'getter method',
  },
  {
    label: 'setter',
    prefix: 'set',
    body: 'public void set${1:Name}(${2:String} ${3:name}) {\n\tthis.${3:name} = ${3:name};\n}',
    description: 'setter method',
  },
  {
    label: 'private field',
    prefix: 'pf',
    body: 'private ${1:String} ${2:name};',
    description: 'private field',
  },
  {
    label: 'System.out.println',
    prefix: 'sout',
    body: 'System.out.println(${1});',
    description: 'System.out.println',
  },
  {
    label: 'System.out.printf',
    prefix: 'soutf',
    body: 'System.out.printf("${1:%s}%n", ${2});',
    description: 'System.out.printf',
  },
  {
    label: 'lambda expression',
    prefix: 'lambda',
    body: '(${1:x}) -> ${2:expression}',
    description: 'lambda expression',
  },
  {
    label: 'stream',
    prefix: 'stream',
    body: '${1:collection}.stream()\n\t.filter(${2:x} -> ${3:condition})\n\t.map(${4:x} -> ${5:expression})\n\t.collect(Collectors.toList());',
    description: 'stream pipeline',
  },
  {
    label: 'package',
    prefix: 'package',
    body: 'package ${1:com.example};',
    description: 'package declaration',
  },
  {
    label: 'import',
    prefix: 'import',
    body: 'import ${1:java.util.*};',
    description: 'import statement',
  },
];
