import type { LanguageSnippet } from '../types';

export const phpSnippets: LanguageSnippet[] = [
  {
    label: 'PHP tags',
    prefix: 'php',
    body: '<?php\n${1}\n?>',
    description: 'PHP tags',
  },
  {
    label: 'if statement',
    prefix: 'if',
    body: 'if (${1:condition}) {\n\t${2}\n}',
    description: 'if statement',
  },
  {
    label: 'if-else statement',
    prefix: 'ife',
    body: 'if (${1:condition}) {\n\t${2}\n} else {\n\t${3}\n}',
    description: 'if-else statement',
  },
  {
    label: 'elseif',
    prefix: 'elif',
    body: 'elseif (${1:condition}) {\n\t${2}\n}',
    description: 'elseif statement',
  },
  {
    label: 'for loop',
    prefix: 'for',
    body: 'for ($$${1:i} = 0; $$${1:i} < ${2:count}; $$${1:i}++) {\n\t${3}\n}',
    description: 'for loop',
  },
  {
    label: 'foreach loop',
    prefix: 'foreach',
    body: 'foreach ($$${1:array} as $$${2:value}) {\n\t${3}\n}',
    description: 'foreach loop',
  },
  {
    label: 'foreach with key',
    prefix: 'foreachk',
    body: 'foreach ($$${1:array} as $$${2:key} => $$${3:value}) {\n\t${4}\n}',
    description: 'foreach with key',
  },
  {
    label: 'while loop',
    prefix: 'while',
    body: 'while (${1:condition}) {\n\t${2}\n}',
    description: 'while loop',
  },
  {
    label: 'do-while loop',
    prefix: 'dowhile',
    body: 'do {\n\t${1}\n} while (${2:condition});',
    description: 'do-while loop',
  },
  {
    label: 'switch statement',
    prefix: 'switch',
    body: 'switch (${1:expression}) {\n\tcase ${2:value}:\n\t\t${3}\n\t\tbreak;\n\tdefault:\n\t\t${4}\n\t\tbreak;\n}',
    description: 'switch statement',
  },
  {
    label: 'try-catch',
    prefix: 'try',
    body: 'try {\n\t${1}\n} catch (${2:Exception} $$${3:e}) {\n\t${4}\n}',
    description: 'try-catch block',
  },
  {
    label: 'try-catch-finally',
    prefix: 'tryf',
    body: 'try {\n\t${1}\n} catch (${2:Exception} $$${3:e}) {\n\t${4}\n} finally {\n\t${5}\n}',
    description: 'try-catch-finally block',
  },
  {
    label: 'function',
    prefix: 'func',
    body: 'function ${1:name}(${2:params}): ${3:void} {\n\t${4}\n}',
    description: 'function definition',
  },
  {
    label: 'class',
    prefix: 'class',
    body: 'class ${1:ClassName} {\n\tpublic function __construct(${2:params}) {\n\t\t${3}\n\t}\n}',
    description: 'class definition',
  },
  {
    label: 'class with inheritance',
    prefix: 'classi',
    body: 'class ${1:ClassName} extends ${2:BaseClass} {\n\tpublic function __construct(${3:params}) {\n\t\tparent::__construct(${4});\n\t\t${5}\n\t}\n}',
    description: 'class with inheritance',
  },
  {
    label: 'interface',
    prefix: 'interface',
    body: 'interface ${1:InterfaceName} {\n\tpublic function ${2:method}(${3:params}): ${4:returnType};\n}',
    description: 'interface definition',
  },
  {
    label: 'trait',
    prefix: 'trait',
    body: 'trait ${1:TraitName} {\n\t${2}\n}',
    description: 'trait definition',
  },
  {
    label: 'public method',
    prefix: 'pubm',
    body: 'public function ${1:name}(${2:params}): ${3:void} {\n\t${4}\n}',
    description: 'public method',
  },
  {
    label: 'private method',
    prefix: 'privm',
    body: 'private function ${1:name}(${2:params}): ${3:void} {\n\t${4}\n}',
    description: 'private method',
  },
  {
    label: 'protected method',
    prefix: 'protm',
    body: 'protected function ${1:name}(${2:params}): ${3:void} {\n\t${4}\n}',
    description: 'protected method',
  },
  {
    label: 'constructor',
    prefix: 'ctor',
    body: 'public function __construct(${1:params}) {\n\t${2}\n}',
    description: 'constructor',
  },
  {
    label: 'getter',
    prefix: 'get',
    body: 'public function get${1:Name}(): ${2:type} {\n\treturn $$this->${3:property};\n}',
    description: 'getter method',
  },
  {
    label: 'setter',
    prefix: 'set',
    body: 'public function set${1:Name}(${2:type} $$${3:value}): void {\n\t$$this->${4:property} = $$${3:value};\n}',
    description: 'setter method',
  },
  {
    label: 'echo',
    prefix: 'echo',
    body: 'echo ${1};',
    description: 'echo statement',
  },
  {
    label: 'print_r',
    prefix: 'pr',
    body: 'print_r(${1});',
    description: 'print_r',
  },
  {
    label: 'var_dump',
    prefix: 'vd',
    body: 'var_dump(${1});',
    description: 'var_dump',
  },
  {
    label: 'namespace',
    prefix: 'namespace',
    body: 'namespace ${1:App};',
    description: 'namespace declaration',
  },
  {
    label: 'use',
    prefix: 'use',
    body: 'use ${1:Namespace\\\\Class};',
    description: 'use statement',
  },
  {
    label: 'require',
    prefix: 'require',
    body: "require '${1:file.php}';",
    description: 'require statement',
  },
  {
    label: 'require_once',
    prefix: 'requireonce',
    body: "require_once '${1:file.php}';",
    description: 'require_once statement',
  },
  {
    label: 'array',
    prefix: 'arr',
    body: "$$${1:array} = [${2}];",
    description: 'array declaration',
  },
  {
    label: 'array_map',
    prefix: 'arrmap',
    body: 'array_map(function($$${1:item}) {\n\treturn ${2};\n}, $$${3:array});',
    description: 'array_map',
  },
  {
    label: 'array_filter',
    prefix: 'arrfilter',
    body: 'array_filter($$${1:array}, function($$${2:item}) {\n\treturn ${3};\n});',
    description: 'array_filter',
  },
];
