import type { LanguageSnippet } from '../types';

export const pythonSnippets: LanguageSnippet[] = [
  {
    label: 'if statement',
    prefix: 'if',
    body: 'if ${1:condition}:\n\t${2:pass}',
    description: 'if statement',
  },
  {
    label: 'if-else statement',
    prefix: 'ife',
    body: 'if ${1:condition}:\n\t${2:pass}\nelse:\n\t${3:pass}',
    description: 'if-else statement',
  },
  {
    label: 'if-elif-else',
    prefix: 'ifel',
    body: 'if ${1:condition}:\n\t${2:pass}\nelif ${3:condition}:\n\t${4:pass}\nelse:\n\t${5:pass}',
    description: 'if-elif-else statement',
  },
  {
    label: 'for loop',
    prefix: 'for',
    body: 'for ${1:item} in ${2:iterable}:\n\t${3:pass}',
    description: 'for loop',
  },
  {
    label: 'for range loop',
    prefix: 'forr',
    body: 'for ${1:i} in range(${2:n}):\n\t${3:pass}',
    description: 'for loop with range',
  },
  {
    label: 'for enumerate',
    prefix: 'fore',
    body: 'for ${1:i}, ${2:item} in enumerate(${3:iterable}):\n\t${4:pass}',
    description: 'for loop with enumerate',
  },
  {
    label: 'while loop',
    prefix: 'while',
    body: 'while ${1:condition}:\n\t${2:pass}',
    description: 'while loop',
  },
  {
    label: 'function definition',
    prefix: 'def',
    body: 'def ${1:name}(${2:params}):\n\t"""${3:docstring}"""\n\t${4:pass}',
    description: 'function definition',
  },
  {
    label: 'async function',
    prefix: 'adef',
    body: 'async def ${1:name}(${2:params}):\n\t"""${3:docstring}"""\n\t${4:pass}',
    description: 'async function definition',
  },
  {
    label: 'class definition',
    prefix: 'class',
    body: 'class ${1:ClassName}:\n\t"""${2:docstring}"""\n\t\n\tdef __init__(self${3:, params}):\n\t\t${4:pass}',
    description: 'class definition',
  },
  {
    label: 'class with inheritance',
    prefix: 'classi',
    body: 'class ${1:ClassName}(${2:BaseClass}):\n\t"""${3:docstring}"""\n\t\n\tdef __init__(self${4:, params}):\n\t\tsuper().__init__(${5})\n\t\t${6:pass}',
    description: 'class with inheritance',
  },
  {
    label: 'try-except',
    prefix: 'try',
    body: 'try:\n\t${1:pass}\nexcept ${2:Exception} as ${3:e}:\n\t${4:pass}',
    description: 'try-except block',
  },
  {
    label: 'try-except-finally',
    prefix: 'tryf',
    body: 'try:\n\t${1:pass}\nexcept ${2:Exception} as ${3:e}:\n\t${4:pass}\nfinally:\n\t${5:pass}',
    description: 'try-except-finally block',
  },
  {
    label: 'with statement',
    prefix: 'with',
    body: 'with ${1:expression} as ${2:target}:\n\t${3:pass}',
    description: 'with statement (context manager)',
  },
  {
    label: 'open file',
    prefix: 'openf',
    body: "with open('${1:filename}', '${2:r}') as ${3:f}:\n\t${4:content = f.read()}",
    description: 'open file with context manager',
  },
  {
    label: 'lambda',
    prefix: 'lambda',
    body: 'lambda ${1:args}: ${2:expression}',
    description: 'lambda expression',
  },
  {
    label: 'list comprehension',
    prefix: 'lc',
    body: '[${1:expression} for ${2:item} in ${3:iterable}]',
    description: 'list comprehension',
  },
  {
    label: 'list comprehension with condition',
    prefix: 'lcc',
    body: '[${1:expression} for ${2:item} in ${3:iterable} if ${4:condition}]',
    description: 'list comprehension with condition',
  },
  {
    label: 'dictionary comprehension',
    prefix: 'dc',
    body: '{${1:key}: ${2:value} for ${3:item} in ${4:iterable}}',
    description: 'dictionary comprehension',
  },
  {
    label: 'set comprehension',
    prefix: 'sc',
    body: '{${1:expression} for ${2:item} in ${3:iterable}}',
    description: 'set comprehension',
  },
  {
    label: 'main block',
    prefix: 'main',
    body: 'if __name__ == "__main__":\n\t${1:main()}',
    description: 'main block',
  },
  {
    label: 'import',
    prefix: 'imp',
    body: 'import ${1:module}',
    description: 'import statement',
  },
  {
    label: 'from import',
    prefix: 'from',
    body: 'from ${1:module} import ${2:name}',
    description: 'from import statement',
  },
  {
    label: 'property decorator',
    prefix: 'prop',
    body: '@property\ndef ${1:name}(self):\n\t"""${2:docstring}"""\n\treturn self._${1:name}',
    description: 'property decorator',
  },
  {
    label: 'static method',
    prefix: 'static',
    body: '@staticmethod\ndef ${1:name}(${2:params}):\n\t"""${3:docstring}"""\n\t${4:pass}',
    description: 'static method',
  },
  {
    label: 'class method',
    prefix: 'classm',
    body: '@classmethod\ndef ${1:name}(cls${2:, params}):\n\t"""${3:docstring}"""\n\t${4:pass}',
    description: 'class method',
  },
  {
    label: 'dataclass',
    prefix: 'dataclass',
    body: 'from dataclasses import dataclass\n\n@dataclass\nclass ${1:ClassName}:\n\t${2:field}: ${3:type}',
    description: 'dataclass definition',
  },
];
