// <auto-generated />
using CloudCode.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CloudCode.Infrastructure.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260315000000_AddPremiumToUsers")]
partial class AddPremiumToUsers
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
}
