// <auto-generated />
using System;
using CloudCode.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudCode.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260314120000_AddQuizEntities")]
    partial class AddQuizEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
